//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstagramClone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friendship
    {
        public int User_Id { get; set; }
        public string Friends { get; set; }
        public string Friend_Requests { get; set; }
    }
}
